### ISSUE TITLE
SQLite Support?

### ISSUE THREAD

**Issue by andykais** [benjie/prettier-plugin-pg#7]
Hi! Thanks for working on this project! I was wondering if it will work with sqlite sql. I dont know all the syntax, but so far as I know, sqlite is [nearly a superset of standard sql](https://www.sqlite.org/lang.html)

**Comment by benjie** [comment]
It will not be a goal of the project (at least not initially); but likely it will work for much of it since PostgreSQL is fairly standards-compliant.

**Comment by andykais** [comment]
ok, thanks for answering
